spring:


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/alterx}
      client:
        registration:
          notification-service-user:
            client-id: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_ID:notification-service}
            client-secret: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_SECRET:notification-service-secret}
          notification-service-org:
            client-id: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_ID:notification-service}
            client-secret: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_SECRET:notification-service-secret}
          notification-service-change:
            client-id: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_ID:notification-service}
            client-secret: ${KEYCLOAK_NOTIFICATION_SERVICE_CLIENT_SECRET:notification-service-secret}
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/alterx}/protocol/openid-connect/token

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8086}

feign:
  clients:
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8082}
    org-service:
      url: ${ORG_SERVICE_URL:http://localhost:8083}
    change-service:
      url: ${CHANGE_SERVICE_URL:http://localhost:8080}